LINECOLOR = 'rgba(33, 37, 41, 1)'

CUSTOM_BLUE = '#2766E8'
CUSTOM_GREY = '#212529'
CUSTOM_RED = '#E83283'
CUSTOM_YELLOW = '#E8B84A'

CATEGORY_COLORS = {
    'MUSIC': CUSTOM_YELLOW,
    'EDUCATION': CUSTOM_BLUE,
    'WORK': CUSTOM_RED,
    'PROGRAMMING': CUSTOM_BLUE,
    'LANGUAGES': CUSTOM_RED,
    'OTHER SKILLS': CUSTOM_GREY,
}
