LINECOLOR = 'rgba(33, 37, 41, 1)'

_CUSTOM_BLUE = '#2766E8'
_CUSTOM_RED = '#E83F8E'
_CUSTOM_YELLOW = '#E8A510'
_CUSTOM_GREY = '#212529'

CATEGORY_COLORS = {
    'MUSIC': _CUSTOM_YELLOW,
    'EDUCATION': _CUSTOM_BLUE,
    'WORK': _CUSTOM_RED,
    'PROGRAMMING': _CUSTOM_GREY,
    'LANGUAGES': _CUSTOM_GREY,
    'OTHER SKILLS': _CUSTOM_GREY,
}
