name: Daily Deployment
on:
  schedule:
  # - cron: "0 0 * * *"
  - cron: "*/10 * * * *"
jobs:
  daily-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: git commit --allow-empty -m "Daily Deployment"
      - run: git push
