name: Daily Deployment

on:
#  schedule:  # Does not trigger automated deploy on render
#  - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  daily-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
    - run: |
        date > today
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name "fschackert"
        git commit today -m "Daily Deployment"
        git push
