name: Daily Deployment

on:
  schedule:
  # - cron: "0 0 * * *"
  - cron: "*/10 * * * *"
  workflow_dispatch:
      
jobs:
  daily-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        date > today.txt
        git config user.name "fschackert"
        git commit --allow-empty -m "Daily Deployment"
        git push
