name: Daily Deployment

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
      
jobs:
  daily-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        date > today
        git config user.email ${{ secrets.EMAIL }}
        git config user.name "fschackert"
        git commit today -m "Daily Deployment"
        git push
