name: Daily Deployment

on:
  schedule:
  # - cron: "0 0 * * *"
  - cron: "*/10 * * * *"
  workflow_dispatch:
      
jobs:
  daily-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: Make an empty commit
        run: git commit --allow-empty -m "Daily Deployment"
      - name: Push empty commit
        run: git push
