name: Daily Deployment

on:
  schedule:
  # - cron: "0 0 * * *"
  - cron: "*/10 * * * *"
  workflow_dispatch:
      
jobs:
  daily-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          branch: main
      - run: git commit --allow-empty -m "Daily Deployment"
      - run: git push origin main
