name: Daily Deployment

on:
  schedule:
  # - cron: "0 0 * * *"
  - cron: "*/10 * * * *"
  workflow_dispatch:
      
jobs:
  daily-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit --allow-empty -m "Daily Deployment"
          git push
